---

- name: Download SoftEther VPN
  get_url:
    url: "https://www.softether-download.com/files/softether/v4.43-9799-beta-2023.08.31-tree/Linux/SoftEther_VPN_Server/64bit_-_Intel_x64_or_AMD64/softether-vpnserver-v4.43-9799-beta-2023.08.31-linux-x64-64bit.tar.gz"
    dest: /tmp/softether-vpnserver.tar.gz

- name: Extract SoftEther VPN
  unarchive:
    src: /tmp/softether-vpnserver.tar.gz
    dest: /opt
    remote_src: true

- name: Debian OS Update
  apt:
    update_cache: true
    upgrade: yes
  when: ansible_os_family == "Debian"

- name: Install Compiler component Debian family
  apt:
    name:
    - gcc
    - make
    state: present
  when: ansible_os_family == "Debian"

- name: Install Compiler component RH family
  yum:
    name:
    - gcc
    - make
    state: present
  when: ansible_os_family == "RedHat"

- name: Compile SoftEther VPN
  shell: |
    cd /opt/vpnserver
    make
  args:
    creates: /opt/vpnserver/vpnserver

- name: Set permissions
  file:
    path: /opt/vpnserver
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Create systemd service file
  copy:
    dest: /etc/systemd/system/vpnserver.service
    content: |
      [Unit]
      Description=SoftEther VPN Server
      After=network.target

      [Service]
      Type=forking
      ExecStart=/opt/vpnserver/vpnserver start
      ExecStop=/opt/vpnserver/vpnserver stop

      [Install]
      WantedBy=multi-user.target

- name: Reload systemd daemon
  systemd:
    daemon_reload: yes

